added Christoph Zinser
Danybba/TEA23 pull request #50
Opened 2024-02-08 15:07 UTC by DerChristoph-2210

2024-02-08 15:13 UTC, leventkanca approved these changes

2024-02-08 15:26 UTC, glutto-3001 requested changes
delete name Tom Gluth in line 15 and christoph_zinser in line 22

2024-02-08 16:08 UTC, glutto-3001 approved these changes

2024-02-08 16:10 UTC, glutto-3001 requested changes
delete dublicate name Simon Kieslich

2024-02-09 15:38 UTC, lronman00 approved these changes

2024-02-13 09:31 UTC, glutto-3001 approved these changes

2024-02-13 09:31 UTC, merged